services:
  db:
    image: postgres:16.3
    container_name: postgres-blog
    environment:
      POSTGRES_DB: blogify
      POSTGRES_USER: swap
      POSTGRES_PASSWORD: root
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
